name: Build

on:
  workflow_dispatch:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_typewriterExternalUsername: ${{ secrets.TYPEWRITER_REPO_USERNAME }}
      ORG_GRADLE_PROJECT_typewriterExternalPassword: ${{ secrets.TYPEWRITER_REPO_PASSWORD }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Install JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          check-latest: true

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run build & publish with Gradle Wrapper
        if: github.ref == 'refs/heads/master'
        run: chmod +x ./gradlew && ./gradlew publish

      - name: Run build with Gradle Wrapper
        if: github.ref != 'refs/heads/master'
        run: chmod +x ./gradlew && ./gradlew build

      - name: Create Release
        if: github.ref != 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ github.ref_name }}: ${{ github.event.head_commit.message }} (${{ github.sha }})'
          prerelease: ${{ github.ref != 'refs/heads/master' }}
          tag_name: ${{ github.ref_name }}-${{ github.sha }}